### ISSUE TITLE
Why elixir base trie when we have ets ?? ( trie DS )

### ISSUE THREAD

**Issue by Rustixir** [dimitarvp/trie#9]
Hi. Ets internally implement judy array. Actually 
Judy array is family of trie/radix-tree and etc. 

When we have ets ( c based, without garbage )
Why is need to elixir based trie ?!

Just I want more know for myself

**Comment by dimitarvp** [comment]
> Ets internally implement judy array. Actually Judy array is family of trie/radix-tree and etc.

Hey, back in 2016 I didn't know that. 😃

This project was just an exercise. I open-sourced it in case somebody was struggling with similar algorithms -- or just using Elixir in general -- and needed an inspiration. That's the reason this mini-project exists.
